me2u/urls.py
#  * This file is part of me2u project.
#  * (c) Ochui Princewill Patrick <ochui.princewill@gmail.com>
#  * For the full copyright and license information, please view the "LICENSE.md"
#  * file that was distributed with this source code.
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
]

urlpatterns += i18n_patterns(
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('exchange.urls')),
)

accounts/models.py
#  * This file is part of me2u project.
#  * (c) Ochui Princewill Patrick <ochui.princewill@gmail.com>
#  * For the full copyright and license information, please view the "LICENSE.md"
#  * file that was distributed with this source code.

from django.contrib.auth.models import AbstractUser
from django.db import models

from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from contact.models import Contact
from django_countries.fields import CountryField

class CustomUser(AbstractUser):
    
    PHONE_NUMBER_STATUS_CHOICES = (
        ('0', _('NOT VERIFIED')),
        ('1', _('VERIFIED'))
    )

    GENDER = (
        ('M', _('MALE')),
        ('F', _('FEMALE'))
    )

    avatar = models.ImageField(_("avatar"), upload_to='avatars/%Y/%m/%d/', blank=True)
    gender = models.CharField(_("gender"), max_length=50, choices=GENDER)
    date_of_birth = models.DateField(_("date of birth"), blank=True, null=True)
    country = CountryField(_('country'), blank_label=_('select country'))
    phone_number = models.CharField(_("phone number"), max_length=20, null=True, blank=True)
    phone_number_status = models.CharField(_("phone number status"), max_length=50, choices=PHONE_NUMBER_STATUS_CHOICES, default='0')
    following = models.ManyToManyField("self", verbose_name=_("following"), through=Contact, symmetrical=False, related_name='followers')

    def get_absolute_url(self):
        return reverse("user_account")
    

templates/dashboard/account_edit.html
{% extends 'base/dashboard_base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="user-content">
    <div class="user-panel">
        <h2 class="user-panel-title">Account Information</h2>
        {% if not verified_email %}<div class="alert-box alert-primary">
            <div class="alert-txt"><em class="ti ti-alert"></em>Confirm your email address</div><a href="#" class="btn btn-sm btn-primary">Resend
                Email</a>
        </div><!-- .alert-box -->{% endif %}
        <ul class="nav nav-tabs nav-tabs-line" role="tablist">
            <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#personal-data">Personal
                    Data</a></li>
            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#wallet-address">Wallet
                    Address</a></li>
            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#notification">Notification</a></li>
        </ul><!-- .nav-tabs-line -->
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="personal-data">
                <form action="{% url 'user_account' %}" method='POST'>
                    {% csrf_token %}
                    <div class="input-item input-with-label">
                        <label for="first-name" class="input-item-label">{% trans "First Name" %}</label>
                        {{form.first_name}}
                    </div>
                    <!-- .input-item -->
                    <div class="input-item input-with-label"><label for="last-name" class="input-item-label">{% trans "Last Name" %}</label>
                    {{form.last_name}}
                    </div>
                    <!-- .input-item -->
                    <div class="input-item input-with-label">
                        <label for="mobile-number" class="input-item-label">{% trans "Mobile Number" %} </label>
                        {{form.phone_number}}
                    </div>
                    <!-- .input-item -->
                    <div class="row">
                        <div class="col-md-6">
                            <div class="input-item input-with-label">
                            <label for="date-of-birth" class="input-item-label">{% trans "Date of Birth" %}</label>
                            {{form.date_of_birth}}
                        </div>
                    <!-- .input-item -->
                    </div><!-- .col -->
                        <div class="col-md-6">
                            <div class="input-item input-with-label">
                                <label for="nationality" class="input-item-label">Nationality</label>
                                {{form.country}}
                            </div><!-- .input-item -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                    <div class="gaps-1x"></div><!-- 10px gap -->
                    <div class="d-sm-flex justify-content-between align-items-center"><button class="btn btn-primary">Update</button>
                        <div class="gaps-2x d-sm-none"></div><span class="color-success"><em class="ti ti-check-box"></em>
                            All Changes are saved</span>
                    </div>
                </form><!-- form -->
            </div><!-- .tab-pane -->
            <div class="tab-pane fade" id="wallet-address">
                <p>In order to receive your ICOX Tokens, please select your wallet addres and you have
                    to put the address below input box. You will receive ICOX tokens to this address
                    after the Token Sale end.</p>
                <form action="#">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="input-item input-with-label"><label for="swalllet" class="input-item-label">Select
                                    Wallet </label><select class="input-bordered" name="swalllet" id="swalllet">
                                    <option value="eth">Ethereum</option>
                                    <option value="dac">DashCoin</option>
                                    <option value="bic">BitCoin</option>
                                </select></div><!-- .input-item -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                    <div class="input-item input-with-label"><label for="token-address" class="input-item-label">Your
                            Address for tokens:</label><input class="input-bordered" type="text" id="token-address"
                            name="token-address" value="0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae"><span class="input-note">Note:
                            Address should be ERC20-compliant.</span></div><!-- .input-item -->
                    <div class="gaps-2x"></div>
                    <div class="note note-plane note-danger"><em class="fas fa-info-circle"></em>
                        <p>DO NOT USE your exchange wallet address such as Kraken, Bitfinex, Bithumb,
                            Binance etc. You can use MetaMask, MayEtherWallet, Mist wallets etc. Do not
                            use the address if you don’t have a private key of the your address. You
                            WILL NOT receive ICOX Tokens and WILL LOSE YOUR FUNDS if you do.</p>
                    </div>
                    <div class="gaps-3x"></div>
                    <div class="gaps-1x"></div><!-- 10px gap -->
                    <div class="d-sm-flex justify-content-between align-items-center"><button class="btn btn-primary">Update</button>
                        <div class="gaps-2x d-sm-none"></div><span class="color-success"><em class="ti ti-check-box"></em>
                            Saved your wallet address</span>
                    </div>
                </form><!-- form -->
            </div><!-- .tab-pane -->
            <div class="tab-pane fade" id="notification">
                <p>You can manage your all kind of notification from here.</p>
                <div class="gaps-1x"></div>
                <ul class="notification-list">
                    <li><span>Notify me by email about resumption of sales</span>
                        <div class="padl-2x"><input class="input-switch" type="checkbox" id="rsmpts"><label for="rsmpts"></label></div>
                    </li>
                    <li><span>Notify me by email for latest news</span>
                        <div class="padl-2x"><input class="input-switch" type="checkbox" checked id="lnews"><label for="lnews"></label></div>
                    </li>
                    <li><span>Alert me by email for unusual activity.</span>
                        <div class="padl-2x"><input class="input-switch" type="checkbox" checked id="unuact"><label for="unuact"></label></div>
                    </li>
                </ul>
                <div class="gaps-4x"></div>
                <div class="d-flex justify-content-between align-items-center"><span></span><span class="color-success"><em
                            class="ti ti-check-box"></em> Update Notification Settings</span></div>
            </div><!-- .tab-pane -->
        </div><!-- .tab-content -->
    </div><!-- .user-panel -->
</div><!-- .user-content -->
{% endblock content %}
{% block javascript %}
<script>
$('#id_date_of_birth').datepicker({
    format: 'yyyy-mm-dd'
});
</script>
{% endblock javascript %}

templates/dashboard/create_offer.html
{% extends 'base/dashboard_base.html' %}
{% block content %}{% load i18n %}
<div class="user-content">
    <div class="user-panel">
        <h2 class="user-panel-title">{% trans "Create New Offer" %}</h2>
        {% comment %} <div class="alert-box alert-danger">
            <div class="alert-txt">Confirm your email address</div>
        </div><!-- .alert-box --> {% endcomment %}
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="personal-data">
                <form method='POST' action="{% url 'user_create_offer' %}">
                    {% csrf_token %}
                    <div class="input-item input-with-label">
                        <label for="coin" class="input-item-label">{% trans "Crytocurrency" %}</label>
                        {{form.coin}}
                    </div><!-- .input-item -->
                    <div class="row">
                        <div class="col-md-4">
                            <div class="input-item input-with-label">
                                <label for="rate_per_coin" class="input-item-label">{% trans "Rate Per Coin" %}</label>
                                {{form.rate_per_coin}}
                            </div><!-- .input-item -->
                        </div><!-- .col -->
                        <div class="col-md-4">
                            <div class="input-item input-with-label">
                                <label for="minimum_amount" class="input-item-label">{% trans "Minimum Amount" %}</label>
                                {{form.minimum_amount}}
                            </div><!-- .input-item -->
                        </div><!-- .col -->
                        <div class="col-md-4">
                            <div class="input-item input-with-label">
                                <label for="maximum_amount" class="input-item-label">{% trans 'Maximum Amount' %}</label>
                                {{form.maximum_amount}}
                            </div><!-- .input-item -->
                        </div><!-- .col -->
                    </div><!-- .row -->
                    <div class="row">
                        <div class="col-md-6">
                            <div class="input-item input-with-label">
                                <label for="duration" class="input-item-label">{% trans 'Duration' %}</label>
                                <input class="input-bordered date-picker" type="text" id="date-of-birth" name="date-of-birth">
                            </div><!-- .input-item -->
                        </div><!-- .col -->
                        <div class="col-md-6">
                            <div class="input-item input-with-label">
                                <label for="location" class="input-item-label">{% trans "Location" %}</label>
                                {{form.location}}
                            </div><!-- .input-item -->
                        </div><!-- .col -->
                    </div><!-- .row -->

                    <div class="input-item input-with-label">
                        <label for="terms" class="input-item-label">{% trans "Terms" %}</label>
                        {{form.terms}}
                    </div><!-- .input-item -->
                    <div class="input-item input-with-label">
                        <label for="instructions" class="input-item-label">{% trans "Instructions" %}</label>
                        {{form.instructions}}
                    </div><!-- .input-item -->
                    <div class="gaps-1x"></div><!-- 10px gap -->
                    <div class="d-sm-flex justify-content-between align-items-center">
                        <button class="btn btn-primary">{% trans "Create Offer" %}</button>
                    </div>
                </form><!-- form -->
            </div><!-- .tab-pane -->
        </div><!-- .tab-content -->
    </div><!-- .user-panel -->
</div><!-- .user-content -->
{% endblock content %}

templates/dashboard/create_trade.html
{% extends 'base/dashboard_base.html' %}
{% load static %}{% load i18n %}
{% block content %}
<div class="user-content">
    <div class="user-panel">
        <h2 class="user-panel-title">{% trans "Open New Trade" %}</h2>
        {% if form.errors %}
        <div class="alert-box alert-danger">
            <div class="alert-txt">{% for error in form.errors %}{{error}}{% endfor %}</div>
        </div><!-- .alert-box -->
        {% endif %}
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="personal-data">
                <form method='POST' action="{% url 'user_create_trade' offer.offer_id %}">
                    {% csrf_token %}
                    <h5 class="user-panel-subtitle">{% trans "01. Select the payment channel" %}</h5>
                    <div class="gaps-1x"></div>
                    <div class="payment-list">
                        <div class="row">
                            {% for radio in form.payment_channel %}
                            <div class="col-md-6 col-sm-6">
                                <div class="payment-item">{{ radio.tag }}<label for="{{ radio.id_for_label }}">
                                        <div class="payment-icon payment-icon-usd"><em class="payment-icon fas fa-credit-card"></em></div><span
                                            class="payment-cur">{{ radio.choice_label }}</span>
                                    </label></div>
                            </div><!-- .col -->
                            {% endfor %}
                        </div><!-- .row -->
                    </div><!-- .payment-list -->
                    <div class="gaps-1x"></div>
                    <h5 class="user-panel-subtitle">{% trans "02. Set amount you would like to purchase" %}</h5>
                    <p>To become a part of the ICO Crypto project and purchase of ICOX token will only be
                        possible after payment made and receving an approval. As you like to participate our
                        project, please select payment method and enter the amount of ICOX tokens you wish to
                        purchase. You can buy ICOX tokens using ETH, BTC, LTC or USD. </p>
                    <div class="gaps-1x"></div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="payment-calculator">
                                <div class="payment-get"><label for="paymentGet">{% trans "Rate per coin" %}</label>
                                    <div class="payment-input">
                                    <div class='input-bordered'>
                                    {{offer.rate_per_coin|floatformat:'-3'}}
                                    </div><span class="payment-get-cur payment-cal-cur">USD</span>
                                    </div>
                                </div><em class="ti ti-exchange-vertical"></em>
                                <div class="payment-from"><label for="amount">{% trans "Amount" %}</label>
                                    <div class="payment-input">{{form.amount}}<span class="payment-from-cur payment-cal-cur">{{offer.coin}}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="gaps-2x d-md-none"></div>
                        </div><!-- .col -->
                        <div class="col-md-4">
                            <div class="payment-bonus">
                                <h6 class="payment-bonus-title">Current Bonus</h6><span class="payment-bonus-amount">20%
                                    <span>on pre-sales</span></span><span class="payment-bonus-time">End at -
                                    09 Jul, 2018</span>
                            </div>
                            <div class="gaps-1x d-md-none"></div>
                        </div><!-- .col -->
                    </div><!-- .row -->
                    <div class="gaps-1x"></div>
                    <div class="payment-calculator-note"><i class="fas fa-info-circle"></i>The calculator helps
                        you to convert required currency to ICOX tokens.</div>
                    <div class="gaps-3x"></div>
                    </div><!-- .payment-summary -->
                    <button type="submit" class="btn btn-primary payment-btn">Purchase {{offer.coin}}</button>
                </form><!-- form --><!-- form -->
            </div><!-- .tab-pane -->
        </div><!-- .tab-content -->
    </div><!-- .user-panel -->
</div><!-- .user-content -->
{% endblock content %}

templates/dashboard/home.html
{% extends 'base/dashboard_base.html' %}

templates/dashboard/list_offer.html
{% extends 'base/dashboard_base.html' %}
{% block content %}{% load i18n %}
{% with offers as offer_list %}
<div class="user-content">
    <div class="user-panel">
        <h2 class="user-panel-title">{% trans "My Offers" %}</h2>
    {% if offer_list %}
        <h4>{% trans "Offer Statistics" %}</h4>
        <div class="refferal-statistics">
            <div class="row">
                <div class="col-md-4">
                    <div class="refferal-statistics-item">
                        <h6>{% trans "Offer Count" %}</h6><span>{{offer_list.count}}</span>
                    </div>
                </div><!-- .col -->
                <div class="col-md-4">
                    <div class="refferal-statistics-item">
                        <h6>{% trans "Views Count" %}</h6><span>31</span>
                    </div>
                </div><!-- .col -->
                <div class="col-md-4">
                    <div class="refferal-statistics-item">
                        <h6>{% trans "Total Sale" %}</h6><span>155</span>
                    </div>
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .refferal-statistics -->
        <h4>{% trans "Offer List" %}</h4>
        <table class="data-table refferal-table">
            <thead>
                <tr>
                    <th class="refferal-name"><span>{% trans "Offer" %}</span></th>
                    <th class="refferal-tokens"><span>{% trans "cryptocurrency" %}</span></th>
                    <th class="refferal-bonus"><span>Views</span></th>
                    <th class="refferal-date"><span>Created</span></th>
                    <th class="refferal-channel"><span>Expires</span></th>
                </tr>
            </thead>
            <tbody>
                {% for offer in offer_list %}
                <tr>
                    <td class="refferal-name">{{offer.id}}</td>
                    <td class="refferal-tokens">{{ offer.coin }}</td>
                    <td class="refferal-bonus">8</td>
                    <td class="refferal-date">{{offer.created_at}}</td>
                    <td class="refferal-channel">08-02-2018</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="status status-empty">
                <div class="status-icon"><em class="ti ti-files"></em>
                    <div class="status-icon-sm"><em class="ti ti-close"></em></div>
                </div><span class="status-text">{% trans "You have not created any offer yet! You should create some." %}</span>
                <a href="{% url 'user_create_offer' %}" class="btn btn-primary">{% trans "Create Now" %}</a>
        </div>
        {% endif %}
    </div><!-- .user-panel -->
</div><!-- .user-content -->
{% endwith %}
{% endblock content %}

templates/dashboard/list_trade.html
{% extends 'base/dashboard_base.html' %}
{% block content %}{% load i18n %}
{% with trades as trade_list %}
<div class="user-content">
    <div class="user-panel">
        <h2 class="user-panel-title">{% trans "My Trade Request" %}</h2>
    {% if trade_list %}
        <h4>{% trans "trade Statistics" %}</h4>
        <div class="refferal-statistics">
            <div class="row">
                <div class="col-md-4">
                    <div class="refferal-statistics-item">
                        <h6>{% trans "Trade Count" %}</h6><span>{{trade_list.count}}</span>
                    </div>
                </div><!-- .col -->
                <div class="col-md-4">
                    <div class="refferal-statistics-item">
                        <h6>{% trans "Trade Request" %}</h6><span>31</span>
                    </div>
                </div><!-- .col -->
                <div class="col-md-4">
                    <div class="refferal-statistics-item">
                        <h6>{% trans "Total Sale" %}</h6><span>155</span>
                    </div>
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .refferal-statistics -->
        <h4>{% trans "trade List" %}</h4>
        <table class="data-table refferal-table">
            <thead>
                <tr>
                    <th class="refferal-name"><span>{% trans "Trade" %}</span></th>
                    <th class="refferal-tokens"><span>{% trans "Offer" %}</span></th>
                    <th class="refferal-bonus"><span>{% trans "Currency" %}</span></th>
                    <th class="refferal-date"><span>{% trans "Status" %}</span></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for trade in trade_list %}
                <tr>
                    <td class="refferal-name">{{trade.trade_uid}}</td>
                    <td class="refferal-tokens"><a href="{% url 'offer_details' trade.offer.offer_id %}">{{trade.offer.offer_id}}</a></td>
                    <td class="refferal-bonus">{{trade.offer.coin}}</td>
                    <td class="refferal-date">{{trade.status}}</td>
                    <td><a href="{% url 'user_trade_details' trade.trade_uid %}">view</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="status status-empty">
                <div class="status-icon"><em class="ti ti-files"></em>
                    <div class="status-icon-sm"><em class="ti ti-close"></em></div>
                </div><span class="status-text">{% trans "You have not created any trade yet! You should create some." %}</span>
                <a href="{% url 'user_create_trade' %}" class="btn btn-primary">{% trans "Create Now" %}</a>
        </div>
        {% endif %}
    </div><!-- .user-panel -->
</div><!-- .user-content -->
{% endwith %}
{% endblock content %}

templates/dashboard/trade_details.html
{% extends 'base/dashboard_base.html' %}